### PR TITLE
First Version

### PR DESCRIPTION
**Pull request by sprintyaf**
This is the first version of our product.

We're fetching data about given repository from GitHub (using PyGithub library) and doing some analysis on returned data. 
The goal is to display this information on a web page and to achieve this goal communication between the server and the data analytics module should be improved. Besides that, Front requires some improvements and visualizations which will be done after we resolve the above-mentioned issue.

### CODE REVIEW

**Comment by shoniavika** [comment]
Documentation is missing, I'll create an issue for that

**Comment by vakhokoto** [comment]
Is this tested? I mean if the modules of analytics

**Comment by sprintyaf** [comment]
> Documentation is missing, I'll create an issue for that

Good point! we could use some help on that

**Comment by vakhokoto** [comment]
* I mean if module of anlytics is tested

**Comment by shoniavika** [comment]
Tests are in /src/server/test_analytic.py. Feel free to add more.

**Comment by vakhokoto** [comment]
I would suggest this @enqidu please help him

**Comment by vakhokoto** [comment]
wouldn't is be better to add README first?

**Comment by sprintyaf** [comment]
> wouldn't is be better to add README first?

I'll work on that. We were testing analytics module but it still requires more adequate testing than the file Vika showed us :D

**Comment by vakhokoto** [comment]
@enqidu pay attention to the comments you got the experience in it

**Comment by enqidu** [comment]
Hey guys, check this video on ena-mamuli.sarwmunoeba.com you wont regret it :PPP

**Comment by vakhokoto** [comment]
Okey, let's merge

**Pull request merged**
